version: '3.8'

services:
  api:
    image: 13angs/real-time-chat-api:latest
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    networks:
      - real-time-chat-network
    volumes:
      - type: bind
        source: ./data
        target: /backend/data
  app:
    image: 13angs/real-time-chat:latest
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - real-time-chat-network
    ports:
      - "3000:80"

networks:
  real-time-chat-network:
    name: real-time-chat-network